services:
  - type: web
    name: gate-ae-mocktest
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false